# -*- coding: utf-8 -*-
"""textgame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17-I8Hnitn_p8vEwoE3UIyL1vdbStn37p
"""

story = {
    # Each scene is a key in the dictionary
    "start": {
        "text": "You find yourself in a dark forest. You can go North or East.",
        "choices": {  # Dictionary of choices for this scene
            "1": ("Go North", "north_path"),  # Choice number: (Choice text, Next scene key)
            "2": ("Go East", "east_path")
        }
    },
    "north_path": {
        "text": "You are on a narrow path leading deeper into the forest. You can go back or continue north.",
        "choices": {
            "1": ("Go back", "start"),
            "2": ("Continue north", "deep_forest")
        }
    },
    "east_path": {
        "text": "You walk east and reach a river. You can swim across or go back.",
        "choices": {
            "1": ("Swim across", "river_crossing"),
            "2": ("Go back", "start")
        }
    },
    "deep_forest": {
        "text": "You are lost in the deep forest. There is no way out.",
        # No choices means the end of the game
    },
    "river_crossing": {
        "text": "You swim across the river and find a village. You win!",
        # No choices means the end of the game
    }
}  # Closing the story dictionary

def display_scene(scene):
  print (scene["text"])
  if "choices" in scene:
    for a,(b,_) in scene["choices"].items():
      print(f"{a}.{b}")

def user_input(scene):
      while True:  # Keep asking until a valid choice is made
        try:
            choice = input("Enter your choice: ")
            if choice in scene["choices"]:  # Check if the choice is valid
                return choice
            else:
                print("Invalid choice. Please try again.")
        except ValueError:  # Handle cases where the input is not a number
            print("Invalid input. Please enter a number.")

ec="start"
while True:
  display_scene(story[ec])
  if "choices" not in story[ec]:
    break
  choice= user_input(story[ec])
  ec= story[ec]["choices"][choice][1]